name: Create Preview Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-preview-[0-9]+"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Set Package name
        id: package-name
        run: echo "name=Bromix.Fluent.Uri.${{ env.VERSION }}" >> $GITHUB_OUTPUT
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"
      - name: Restore
        run: dotnet restore
      - name: Build and Pack
        run: dotnet build -c Release -p:Version=${VERSION}
      - name: Publish to NuGet
        run: dotnet nuget push ./Bromix.Fluent.Uri/bin/Release/${{ steps.package-name.outputs.name }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
